spring:
  application:
    name: salon-api
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/salon
    username: admin
    password: admin


server:
  port: 8081

salon:
  name: AR Salon and Day Spa Services
  address: 1234 Main Street
  city: Anytown
  state: ND
  zipcode: 58201
  phone: 555-123-4567

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html